version: '3.8'

volumes:
  app:

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - app:/app
    working_dir: /app
    command: /bin/sh
    tty: true
